---

apiVersion: v1
kind: Service

# Metadata for name
metadata:
  name: nginx-svc
  namespace: default 

# Specification to include ports Selector to connect to the deployment
spec:
  ports:
  - nodePort: 30442 # range is 30000-32768
    port: 80
    protocol: TCP
    targetPort: 80

# Let's define the selector and label to connect to nginx deployment
  selector:
    app: nginx # this label connects this service to deployment
 # creating LoadBalncer type of deployment
  type: LoadBalancer